server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;

  location = /tv {
    return 302 /tv/;
  }

  location /tv/ {
    try_files $uri $uri/ /tv/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
