server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;
  add_header Cache-Control "no-store" always;

  location /api/ {
    proxy_pass http://dino-backend:3000/;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    client_max_body_size 4m;
  }

  location ~ /\. { deny all; }

  location = /console {
    return 302 /console/;
  }
  location /console/ {
    try_files $uri $uri/ /console/index.html;
  }

  location = /tv {
    return 302 /tv/;
  }
  location /tv/ {
    try_files $uri $uri/ /tv/index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
